### ISSUE TITLE
Failed to copy

### ISSUE THREAD

**Issue by respeto** [fann95/C4droid-Shell#2]
I'm still getting this error while trying to compile. I use HTC Droid DNA so i dont have an external sdcard. So the gcc has already installed on internal sdcard. But i got C4Droid_EXT dir  in internal sdcard after compile makefile. And could you please provide some samples? To make sure we are got some problem or not.

**Comment by fann95** [comment]
Failed to copy the error or message? I am  not a developer C4droid and I get the same message, but it does not affect the compilation. You need to ask the author C4droid  about this error.

**Comment by respeto** [comment]
Sorry, i think this only happened to me. If you got that the message to, so no problem. But can you give me an simple samples please? I have trouble when including curl.h and it has error message "... curl_easy_opt ...".
and when i see on terminal it has c4dash error "unexpected word expecting ")";

**Comment by fann95** [comment]
try to fix permissions curl and c4dsh , I think the problem will be solved
